namespace Zen.Compiler;

public enum ErrorCode : uint32
{
	VARIABLE_ASSIGNMENT_IMMUTABLE,

	RETURN_TOP_LEVEL,

	NO_CURRENT_NAMESPACE,

	IDENTIFIER_NOT_FOUND,
	IDENTIFIER_AMBIGUOUS,
	IDENTIFIER_ALREADY_DEFINED,
	IDENTIFIER_ALREADY_DEFINED_SCOPE,

	IMPLICIT_CAST_INVALID,

	FUNCTION_CALL_TOO_MANY_ARGUMENTS,
	FUNCTION_CALL_TOO_FEW_ARGUMENTS,

	OPERATOR_INCOMPATIBLE_TYPES
}