FileVersion = 1
Dependencies = {corlib = "*", corlib = "*"}

[Project]
Name = "Zen"
StartupObject = "Zen.Program"
ProcessorMacros = ["CLI"]

[Configs.Debug.Win64]
DebugCommandArguments = "-workspace=$(WorkspaceDir)/test"

[Configs.Release.Win64]
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/vendor/libtcc/vendor/tcc\", \"$(BuildDir)\")"]
DebugCommandArguments = "-workspace=$(WorkspaceDir)/test"
